appenders=console, file
rootLogger.level=info
rootLogger.appenderRefs=console, file
rootLogger.appenderRef.console.ref=ConsoleAppender
rootLogger.appenderRef.file.ref=FileAppender

appender.console.type=Console
appender.console.name=ConsoleAppender
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=%d{ISO8601} [%t] %-5p (%F:%L) - %m%n

appender.file.type=RollingFile
appender.file.name=FileAppender
appender.file.fileName=target/logs/automation.log
appender.file.filePattern=target/logs/automation-%d{yyyy-MM-dd}.log
appender.file.layout.type=PatternLayout
appender.file.layout.pattern=%d{ISO8601} [%t] %-5p (%F:%L) - %m%n
appender.file.policies.type=Policies
appender.file.policies.time.type=TimeBasedTriggeringPolicy
appender.file.policies.time.interval=1
